### PR TITLE
Update smartcar.ino

### PR DESCRIPTION
**Pull request by gusallaar**

### CODE REVIEW

**Comment by platisd** [comment]
Screenshot from 2022-08-14 21-37-21

Please stop creating pull requests or you will get the entire GitHub organization banned. If you don't understand how git/GitHub works please refer to relevant resources.

**Comment by gusallaar** [comment]
> Screenshot from 2022-08-14 21-37-21
> 
> Please stop creating pull requests or you will get the entire GitHub organization banned. If you don't understand how git/GitHub works please refer to relevant resources.

**Comment by platisd** [comment]
If you are trying to make something compile, **you need to get that to compile in your computer first** and then push it to GitHub.

**Comment by gusallaar** [comment]
Ok. Sorry for this inconvenience. I will stop creating pull requests and find the right way to upload my code.

**Pull request closed without merging**
